### ISSUE TITLE
Error: ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by andresakai** [mmendesas/walnutjs#57]
I'm getting the following error when I try to run, after I updated walnutjs to version 1.0.51: 

`protractor protractor.conf.js`

`root@236b04767951:/bdd# protractor protractor.conf.js 
[13:55:01] I/launcher - Running 1 instances of WebDriver
[13:55:01] I/local - Starting selenium standalone server...
[13:55:02] I/local - Selenium standalone server started at http://172.17.0.2:45820/wd/hub
[13:55:03] E/launcher - Error: ReferenceError: describe is not defined
    at Object.<anonymous> (/bdd/node_modules/walnutjs/src/support/config.test.js:14:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /bdd/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:63:29
    at Array.forEach (<anonymous>)
[13:55:03] E/launcher - Process exited with error code 100
`

**Comment by lfguerreiro** [comment]
Hi,

Change version:

"dependencies": {
    "walnutjs": "**1.0.49**"
  }

New version is not working :(

**Comment by mmendesas** [comment]
Hey guys, @andresakai and @lfguerreiro 

I found the problem that brought some headaches, the cucumber library checks all the files inside the `src` folder, and does some pre-validation. For this case, it breaks because the `jest` module has not yet loaded correctly into the test stream.

Operating properly in version **1.0.52**  please, check it out!

**problem**: The unit test files were in the wrong structure, along with the source files
```sh
/src
    sample.js
    sample.test.js
```
**solution** : Reset the folder structure, separating src and test

```sh
/src
    sample.js
/test
    sample.test.js
```

If you have any other questions or issues, you're really welcome!
